/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopRatedRouteImport } from './routes/top-rated'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as ApiTmdbSplatRouteImport } from './routes/api/tmdb.$'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedRoute = TopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbSplatRoute = ApiTmdbSplatRouteImport.update({
  id: '/api/tmdb/$',
  path: '/api/tmdb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$id': typeof MovieIdRoute
  '/api/tmdb/$': typeof ApiTmdbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/top-rated'
    | '/trending'
    | '/upcoming'
    | '/watchlist'
    | '/movie/$id'
    | '/api/tmdb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/top-rated'
    | '/trending'
    | '/upcoming'
    | '/watchlist'
    | '/movie/$id'
    | '/api/tmdb/$'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/top-rated'
    | '/trending'
    | '/upcoming'
    | '/watchlist'
    | '/movie/$id'
    | '/api/tmdb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  TopRatedRoute: typeof TopRatedRoute
  TrendingRoute: typeof TrendingRoute
  UpcomingRoute: typeof UpcomingRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieIdRoute: typeof MovieIdRoute
  ApiTmdbSplatRoute: typeof ApiTmdbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated': {
      id: '/top-rated'
      path: '/top-rated'
      fullPath: '/top-rated'
      preLoaderRoute: typeof TopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/$': {
      id: '/api/tmdb/$'
      path: '/api/tmdb/$'
      fullPath: '/api/tmdb/$'
      preLoaderRoute: typeof ApiTmdbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  TopRatedRoute: TopRatedRoute,
  TrendingRoute: TrendingRoute,
  UpcomingRoute: UpcomingRoute,
  WatchlistRoute: WatchlistRoute,
  MovieIdRoute: MovieIdRoute,
  ApiTmdbSplatRoute: ApiTmdbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
